language: ruby

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS rails-api-boilerplate_test;'

bundler_args: --without production

before_script:
  - cp config/database.travis.yml config/database.yml
  - bin/rails db:setup RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec rubocop -R
