language: ruby

services:
  - mysql

bundler_args: --without production

before_script:
  - cp config/database.travis.yml config/database.yml
  - bin/rails db:setup RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec rubocop -R
